version: '3.8'  # Specify the Compose file format version

services:
  app:  # Name of the service
    build: 
      context: .  # Path to the directory containing the Dockerfile
    ports:
      - "2000:2000"  # Map port 2000 on the host to port 2000 in the container
    env_file:
      - .env  # Specify the environment file
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: ["npm", "run", "dev"]  # Override CMD if needed
